### ISSUE TITLE
Documentation search

### ISSUE THREAD

**Issue by jennasalau** [DeloitteDigitalAPAC/rhythm-ui#24]
We need to have search capabilities on the documentation site.

https://www.gatsbyjs.org/docs/adding-search/

Only criteria is that if you search a component name eg "rui-button" the associated component page should be the first search result.

It might be worth introducing tagging into the front matter as well.

**Comment by terencejeong** [comment]
Is there a preference with what search library we use?

elasticlunr and js-search are open source, where the former has a gatsby plugin. 

I've also looked at Algolia which also has a gatsby plugin however will have to pay for the usage. 

Personally I'd like to go with either elasticlunr or Algolia because the plugins allow us to define the query in the gatsby-config.js file where as the js-search it looks like we have to make a standard HTTP Get request rather than a query.

**Comment by terencejeong** [comment]
First pass at the Search is in https://github.com/DeloitteDigitalAPAC/rhythm-ui/pull/26 :)
